### PR TITLE
Show departures below stops in nearest departures

### PR DESCRIPTION
**Pull request by laurilehmijoki**

### CODE REVIEW

**Comment by laurilehmijoki** [comment]
Related to #1

**Comment by laurilehmijoki** [comment]
I don't know why sorting does not work correctly for some stops.

Given latitude `60,1998` and longiture `24,975`, the start screen looks like this:

simulator screen shot 1 jan 2017 20 25 48

Now, if I tap the topmost stop, the view looks like this (notice that the order of destinations is different here than on the previous screenshot):

simulator screen shot 1 jan 2017 20 28 07

Why the sorting logic

```swift
.sorted(by: { (departureA, departureB) in
                    departureA.realDepartureTime < departureB.realDepartureTime
                })
```

does not work in the above case?

**Comment by suominentoni** [comment]
Thanks for the PR, Lauri!

I'll take a look at this and the sorting problem tonight.

**Comment by suominentoni** [comment]
I really cannot understand why the order goes wrong with the sorting.

However, judging based on a quick test, the sorting actually seems unneeded. I think the API already returns the departures in a correct order. I've now clicked through maybe thirty stops, and the order has been correct 100% of the time with the sorting removed.

I'm happy to merge this if you just remove the sorting. What do you think?

**Comment by laurilehmijoki** [comment]
Sounds good to me! Thanks for testing.

**Comment by laurilehmijoki** [comment]
Sorting is now removed. I can confirm your observation – the departures seem to be in a correct order without explicit sorting.

**Comment by suominentoni** [comment]
Great! I'll do a final quick test on a real device tonight, and then merge. I'll also aim to submit a release right after merging.

**Comment by suominentoni** [comment]
👍 

Merging this now. Thanks!

A couple of optional todo's related to this feature: showing the destinations on the favourite stops view and the nearest stops view on the Apple Watch app. I'll add these to the todo list on the readme (and probably transfer the todo's from the readme to GitHub issues, which I've been meaning to do for quite a while already).

If you feel like doing more coding for LL, go right ahead!

**Comment by suominentoni** [comment]
I submitted a new release to Apple last night, and it's now waiting for review. Should be in the App Store in a couple of days, I'd guess.

**Comment by suominentoni** [comment]
A new version with this feature included is now available on the App Store. Thanks again!

**Pull request merged**
